[build]
  command = "ng build && ng run serverless-angular-workshop:serverless:production"
  publish = "dist/serverless-angular-workshop/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"

  status = 200
[[plugins]]
  package = "@netlify/plugin-angular-universal"
  
[dev]
  command = "npm run start"
  functions = "netlify/functions"

